[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  DIRECTUS_URL = "https://cod.artpix.cloud"

[[redirects]]
  from = "/assets/*"
  to = "https://cod.artpix.cloud/assets/:splat"
  status = 200
  force = true
